### ISSUE TITLE
model inference error

### ISSUE THREAD

**Issue by 3244we** [longyuewangdcu/Chinese-Llama-2#4]
{'': 0}
Using pad_token, but it is not set yet.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Traceback (most recent call last):
  File "/home/chenjunhao/chinese-llama-2/test/inference_lora.py", line 160, in <module>
    generated_ids = model.generate(inputs=input_ids, attention_mask=attn_mask, generation_config=gen_config)
  File "/home/chenjunhao/.local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/chenjunhao/chinese-llama-2/transformers/src/transformers/generation/utils.py", line 1462, in generate
    return self.sample(
  File "/home/chenjunhao/chinese-llama-2/transformers/src/transformers/generation/utils.py", line 2514, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

every elements in probs are 0

**Comment by seeledu** [comment]
Could you please provide the bash command that you are running？

**Comment by 3244we** [comment]
> 

the all bash command is copied by you

**Comment by 3244we** [comment]
> 

可能是lora的adapter文件夹里面少了added_tokens.json

**Comment by seeledu** [comment]
maybe you make mistake about origin model path and lora model path

**Comment by 3244we** [comment]
> maybe you make mistake about origin model path and lora model path
I just append added_tokens.json and it becomes normal.
